#pragma once

#include "NativeGameplayTags.h"

namespace GameplayViewModeTags
{
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace GameplayLocomotionModeTags
{
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
}

namespace GameplayStanceTags
{
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
}

namespace GameplayGaitTags
{
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace GameplayOverlayModeTags
{
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rifle)
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pistol)
}

namespace GameplayLocomotionActionTags
{
	GAMEPLAYLOCOMOTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdolling)
}